import type { Metadata } from "next";
import { Inter, Gilda_Display, Barlow } from "next/font/google";
import "./globals.css";
import Provider from "./providers";
import Footer from "./_components/Footer/Footer";
import Nav from "./_components/NavBar/Nav";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap",
});

const gilda = Gilda_Display({
    subsets: ["latin"],
    variable: "--font-gilda-display",
    display: "swap",
    weight: "400",
});

const barlow = Barlow({
    subsets: ["latin"],
    variable: "--font-barlow",
    display: "swap",
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${gilda.variable} ${barlow.variable}`}
            >
                <Provider>
                    <Nav />
                    {children}
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
