import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./providers";
import Footer from "./_components/Footer/Footer";
import Header from "./_components/Header/Header";
import Nav from "./_components/NavBar/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Nav/>
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
